name: Sync S3 Bucket

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-bucket:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Get AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Change directory to frontend
        run: |
          cd frontend

      - name: Run build
        run: |
          npm run build

      - name: Sync S3 bucket
        run: |
          aws s3 sync dist s3://${{ secrets.S3_BUCKET_NAME }}
      
      - name: Invalidate CloudFront distribution
        run: |
          aws cloudfront invalidate-distribution --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
